CREATE TABLE IF NOT EXISTS vehiclelogs (
	id INT AUTO_INCREMENT NOT NULL,
    vehicle_id VARCHAR(12) NOT NULL,
    action VARCHAR(5) NOT NULL,
    time DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CHECK (LENGTH(vehicle_id) > 6)
);